name: Release on GitHub Pages
on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4

      - name: Build | Résumé
        uses: xu-cheng/latex-action@v3
        with:
          latexmk_shell_escape: true
          latexmk_use_xelatex: true
          root_file: ./resume.tex

      - name: Stage | PDFs
        run: |
          mkdir pub/
          mv resume.pdf pub/

      - name: Setup | Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Setup | j2cli
        run: |
          pip3 install --user --upgrade j2cli
          j2 --version

      - name: Stage | Index
        run: |
          PDF='resume.pdf' j2 templates/index.html.j2 > pub/index.html

      - name: Stage | Embed
        run: |
          PDF='resume.pdf' j2 templates/embed.html.j2 > pub/embed.html

      - name: Stage | Résumé
        run: |
          PDF='resume.pdf' j2 templates/index.html.j2 > pub/resume.html

      - name: Stage | Résumé, Embed
        run: |
          PDF='resume.pdf' j2 templates/embed.html.j2 > pub/resume-embed.html

      - name: Deploy, Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: pub/
